name: pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: setup python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.14

      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme sphinxcontrib-contentui sphinxcontrib-details-directive sphinx_copybutton furo myst_parser

      - name: Sphinx build
        run: |
          cd pages
          make
          cp ../assets.json build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: pages/build/html
          force_orphan: true
